# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11FjrBNSTVhfdW9Lv3Ry8-NRFfMh4gprS
"""

import numpy as np
from scipy.stats import bernoulli
size = 100000
#given
prob_A = 7/13  
prob_B = 9/13 
prob_AB = 4/13 
data_A = bernoulli.rvs(size = size , p = prob_A)
data_B = bernoulli.rvs(size = size , p = prob_B)
#to find intersection of E and F and find probabilities of E and F
count_AB =0
count_A = 0
count_B = 0
for i in range(size):
  if data_A[i] ==1 and data_B[i]==1:
    count_AB+=1
  if data_A[i] == 1:
    count_A+=1
  if data_B[i] == 1:
    count_B+=1
calc_prob_AB = count_AB/size
calc_prob_A = count_A/size
calc_prob_B  = count_B/size
print(calc_prob_AB)
#since Pr(A|B) = Pr(AB)/Pr(B)
print("The calculated value of Pr(A|B) is " , calc_prob_AB/calc_prob_B , "while theoretical value is" , prob_AB/prob_B )